stack:
  nginx:
    document_root: web
    index: app.php

  php:
    version: 7.1
    modules:
      - pdo_mysql
    deployment:
      install:
        - "sed -i 's/database_host: 127.0.0.1/database_host: mysql/g' app/config/parameters.yml.dist"
        - "sed -i 's/demo.victoire.dev: fr/$DEVFLOW_HOST: fr/g' app/config/parameters.yml.dist"
        - composer install --prefer-dist --no-interaction --optimize-autoloader
        - php bin/console do:s:c
        - mysql -h mysql -u root -proot victoire_demo < ./var/dump/db.sql
        - php bin/console victoire:generate:view-cache
        - php bin/console victoire:widget-css:generate
        - tar -zxvf var/dump/uploads.tar.gz -C web/
        - bower install
        - php bin/console assets:install web --symlink
        - php bin/console mopa:bootstrap:symlink:less
        - php bin/console assetic:dump

  mysql:
    version: 5.5
    user: root
    password: root
    databases:
      - victoire_demo